apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::002006461949:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::002006461949:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TZUX2I2KD82U
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-12T06:25:39Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1490"
  uid: f5a7cb69-4d24-4e9c-89ec-96ab05980f7b
