apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::933461971946:role/UdacityFlaskDeployCBKubectlRole
      username: build
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::933461971946:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5CY4CF94SL4R
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-10T06:32:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1412"
  uid: d930444c-7f4e-43ac-b152-a29dcdc01d2b
